name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.19]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -o alterix ./...

      - name: Test
        run: echo "No tests to run."

      - name: Determine Asset Name
        id: asset-name
        run: echo "::set-output name=name::alterix-${{ matrix.platform }}"
      
      - name: Upload Assets
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./alterix
          asset_name: ${{ steps.asset-name.outputs.name }}
          asset_content_type: application/octet-stream