name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.19]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.platform }}
        run: |
          case ${{ matrix.platform }} in
            ubuntu-latest)
              go build -o alterix-linux
              ;;
            macos-latest)
              go build -o alterix-macos
              ;;
            windows-latest)
              go build -o alterix-windows.exe
              ;;
          esac

      - name: Test
        run: echo "No tests to run."

      - name: Upload Assets
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            case ${{ matrix.platform }} in
              ubuntu-latest)
                ./alterix-linux
                ;;
              macos-latest)
                ./alterix-macos
                ;;
              windows-latest)
                ./alterix-windows.exe
                ;;
            esac
          asset_name: |
            case ${{ matrix.platform }} in
              ubuntu-latest)
                alterix-linux
                ;;
              macos-latest)
                alterix-macos
                ;;
              windows-latest)
                alterix-windows.exe
                ;;
            esac
          asset_content_type: application/octet-stream