name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest] # Add your desired platforms here
        go-version: [1.19]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set Release Version
      run: echo "::set-env name=RELEASE_VERSION::v1.0.0" # Replace with your desired release version

    - name: Build
      run: go build -v ./...

    - name: Test
      run: echo "No tests to run."

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path/to/your/asset.zip # Replace with the path to your built asset
        asset_name: YourAssetName.zip # Replace with the desired name for your asset
        asset_content_type: application/zip