name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.19]
        asset-name: [alterix-linux, alterix-macos, alterix-windows] # Different names for different platforms

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -o ${{ matrix.asset-name }} ./...

    - name: Test
      run: echo "No tests to run."

    - name: Upload Assets
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ matrix.asset-name }} # Update the path of the generated file
        asset_name: ${{ matrix.asset-name }} # Update the name of the generated file
        asset_content_type: application/octet-stream